<?php if (Auth::check()): ?>
    <table>
        <tr>
            <td>Money: <?= money_format(Auth::player()->money) ?></td>
            <td>Income: <?= income_format(Auth::player()->income) ?></td>
            <td>Attack: <?= attack_format(Auth::player()->attack) ?></td>
            <td>Defence: <?= defence_format(Auth::player()->defence) ?></td>
        </tr>
    </table>
<?php endif ?>

<table>
    <tr>
        <td>
            <a href="/">Home</a> &nbsp;
            <?php if (Auth::check()): ?>
                <a href="/units">Units</a> &nbsp;
                <a href="/buildings">Buildings</a> &nbsp;
            <?php else: ?>
                <a href="/about">About</a>
            <?php endif ?>
        </td>
        <td>
            <?php if (Auth::check()): ?>
                <a href="/auth/signout">Sign out</a>
            <?php else: ?>
                <a href="/auth/signin">Sign in</a> &nbsp;
                <a href="/auth/signup">Sign up</a>
            <?php endif ?>
        </td>
    </tr>
</table>