<?= view('layouts.header', [ 'title' => 'Units' ]) ?>

<h1>Units</h1>
<table>
    <?php foreach ($units as $unit): ?>
        <tr>
            <td>
                <img width="150" src="/images/units/<?= $unit->unit_id ?>.jpg">
            </td>
            <td>
                <h3><?= $unit->name ?></h3>
                <p>Attack: <?= attack_format($unit->attack) ?> - Defence: <?= defence_format($unit->defence) ?></p>
            </td>
            <td>
                <p>Price: <?= money_format($unit->price) ?></p>
            </td>
            <td>
                <p><?= $unit->amount ?></p>
            </td>
            <td>
                <p><a href="/buy_units?unit_id=<?= $unit->unit_id ?>&amount=1">Buy</a></p>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?= view('layouts.footer') ?>