<?= view('layouts.header', [ 'title' => 'Sign in' ]) ?>

<h1>Sign in</h1>

<?php if (isset($_SESSION['errors'])): ?>
    <ul>
        <?php foreach ($_SESSION['errors'] as $error): ?>
            <li><?= $error ?></li>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/auth/signin" method="post">
    <div>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" autofocus>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
    </div>
    <div>
        <input type="submit" value="Sign in">
    </div>
</form>

<?= view('layouts.footer') ?>